_commit: 0.6.7
_src_path: gh:georgedouzas/copier-pdm-nox.git
author_email: gdouzas@icloud.com
author_fullname: Georgios Douzas
author_username: georgedouzas
copyright_date: '2023'
copyright_holder: Georgios Douzas
copyright_holder_email: gdouzas@icloud.com
copyright_license: MIT License
project_description: A Python package to create and simulate physics models.
python_package_distribution_name: sage-physics
python_package_import_name: sagephys
python_versions: '>=3.10, <=3.11'
repository_name: sage-physics
repository_namespace: georgedouzas
